apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-dcgm-mock-exporter
  labels:
    app: nvidia-dcgm-exporter
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: gpu-metrics
      scheme: http
  selector:
    matchLabels:
      app: nvidia-dcgm-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-view-nvidia-dcgm-mock-exporter
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-view-nvidia-dcgm-mock-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-view-nvidia-dcgm-mock-exporter
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
